version: '3.8'

services:
  app:
    image: benoitpodwinski/expressvoitures:latest
    container_name: expressvoitures
    restart: always
    ports:
      - "19781:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=db;Database=ExpressVoitures;User=sa;Password=${DB_PASSWORD};Trusted_Connection=False;
    depends_on:
      - db
    volumes:
      - ./keys:/var/keys

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver_data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
    user: "0"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P '${DB_PASSWORD}' -Q 'select 1'"]
      interval: 10s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
    depends_on:
      - db
